# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# compile C with /usr/bin/cc
# compile CXX with /usr/bin/c++
C_FLAGS =  

C_DEFINES = 

C_INCLUDES = -I/home/gautham/Files/CMU/Spring2019/24783_project/trials_2/project/Path_Planning/RF_PP/include -I/home/gautham/Files/CMU/Spring2019/24783_project/trials_2/project/Path_Planning/hiredis/. 

CXX_FLAGS =   -std=gnu++11

CXX_DEFINES = 

CXX_INCLUDES = -I/home/gautham/Files/CMU/Spring2019/24783_project/trials_2/project/Path_Planning/RF_PP/include -I/home/gautham/Files/CMU/Spring2019/24783_project/trials_2/project/Path_Planning/hiredis/. 

