# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# compile C with /usr/bin/cc
C_FLAGS =  

C_DEFINES = 

C_INCLUDES = -I/home/gautham/Files/CMU/Spring2019/24783_project/trials_2/project/Path_Planning/hiredis/. 

